on:
  push:
    branches:
      - testboi
name: 🚀 Deploy website on push to main
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER_02 }}
        username: ${{ secrets.FTP_USERNAME_02 }}
        password: ${{ secrets.FTP_PASSWORD_02 }}
